apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      sendFinished: true
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","incidentUrl":"{{.data.openticket.incidentUrl}}","result":"{{.data.result}}
          ({{.data.evaluation.score}} / 100)"}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: 082734b4-7621-4491-b142-45be85b7547b
