apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      requests:
        - curl --request POST --data
          '{"project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","incident":{"ProblemID":"{{.data.incident.ProblemID}}","ProblemURL":"{{.data.incident.ProblemURL}}","ProblemTitle":"{{.data.incident.ProblemTitle}}","State":"{{.data.incident.State}}","Tags":"{{.data.incident.Tags}}"},"openticket":{"incidentUrl":"{{.data.openticket.incidentUrl}}","incidentNumber":"{{.data.openticket.incidentNumber}}"}}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: e335d827-0ed0-4349-a50b-e51284359394
      sendFinished: true
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"shkeptncontext\":\"{{.shkeptncontext}}\",\
          \"id\":\"{{.id}}\",\"data\":{\"project\":\"{{.data.project}}\",\"serv\
          ice\":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"bridge\":\
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",\"incident\":{\"ProblemID\":\"{{.data.incident.Probl\
          emID}}\",\"ProblemURL\":\"{{.data.incident.ProblemURL}}\",\"Tags\":\"\
          {{.data.incident.Tags}}\",\"ProblemTitle\":\"{{.data.incident.Problem\
          Title}}\",\"State\":\"{{.data.incident.State}}\"}}}'
          https://automation.atlassian.com/pro/hooks/f43475548fea82de26cacbe3dd\
          4b7c1ced7638ff"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 385c73cc-ff32-4c56-b46e-f939e145990a
      sendFinished: false
    - type: sh.keptn.event.notify.triggered
      requests:
        - "curl --header 'Authorization: Api-Token
          {{.env.secret_dynatraceproblemcomment_token}}' --header 'Content-Type:
          application/json' --request POST --data '{\"message\":\"This is a
          comment!\",\"context\":\"cloud-automation-webhook\"}'
          https://syh360.dynatrace-managed.com/e/1c819cc7-d7f5-40d9-b90f-b80c86\
          10a392/api/v2/problems/{{.data.incident.ProblemID}}/comments"
      envFrom:
        - name: secret_dynatraceproblemcomment_token
          secretRef:
            name: dynatrace-problem-comment
            key: token
      subscriptionID: 9b8f7fb2-7deb-419c-b8ec-28c8bae3827f
      sendFinished: true
