apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.openticket.finished
      requests:
        - "curl --request POST --data '{\"type\": \"{{.type}}\" \"project\":
          \"{{.data.project}}\", \"service\": \"{{.data.service}}\", \"stage\":
          \"{{.data.stage}}\", \"shkeptncontext\": \"{{.shkeptncontext}}\",
          \"id\": \"{{.id}}\", \"openticket\": {   \"incidentNumber\":
          \"{{.data.openticket.incidentNumber}}\",   \"incidentUrl\":
          \"{{.data.openticket.incidentUrl}}\"    }}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765"
      subscriptionID: edaef679-8324-453b-84e7-c60dd7f6711a
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Authorization: token
          {{.env.secret_githubsecret_GITHUBTOKEN}}' --request POST --data
          '{\"event_type\":\"openticket\",\"client_payload\":{\"type\":\"{{.typ\
          e}}\",\"project\":\"{{.data.project}}\",\"service\":\"{{.data.service\
          }}\",\"stage\":\"{{.data.stage}}\",\"shkeptncontext\":\"{{.shkeptncon\
          text}}\",\"id\":\"{{.id}}\",\"incident\":{\"ProblemID\":\"{{.data.inc\
          ident.ProblemID}}\",\"ProblemTitle\":\"{{.data.incident.ProblemTitle}}\
          \",\"ProblemURL\":\"{{.data.incident.ProblemURL}}\",\"State\":\"{{.da\
          ta.incident.State}}\",\"Tags\":\"{{.data.incident.Tags}}\"}}}'
          https://api.github.com/repos/dt-robertjahn/rob00334-incident-demo/dis\
          patches"
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: c0d0f7b9-251d-4438-8122-443d6b1b34d9
