apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notifyticket.triggered
      requests:
        - curl --request POST --data
          '{"project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","incident":{"ProblemID":"{{.data.incident.ProblemID}}","ProblemURL":"{{.data.incident.ProblemURL}}","ProblemTitle":"{{.data.incident.ProblemTitle}}","State":"{{.data.incident.State}}","Tags":"{{.data.incident.Tags}}"},"openticket":{"incidentUrl":"{{.data.openticket.incidentURL}}","incidentNumber":"{{.data.openticket.incidentID}}"}}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: e335d827-0ed0-4349-a50b-e51284359394
      sendFinished: true
    - type: sh.keptn.event.notifyticket.triggered
      requests:
        - "curl --header 'Authorization: Api-Token
          {{.env.secret_dynatraceproblemcomment_token}}' --header 'Content-Type:
          application/json' --request POST --data '{\"message\":\"Opened
          Incident {{.data.openticket.incidentID}} in
          [PagerDuty]({{.data.openticket.incidentURL}})\",\"context\":\"cloud-a\
          utomation-webhook\"}'
          https://syh360.dynatrace-managed.com/e/1c819cc7-d7f5-40d9-b90f-b80c86\
          10a392/api/v2/problems/{{.data.incident.PID}}/comments"
      envFrom:
        - name: secret_dynatraceproblemcomment_token
          secretRef:
            name: dynatrace-problem-comment
            key: token
      subscriptionID: 9b8f7fb2-7deb-419c-b8ec-28c8bae3827f
      sendFinished: true
    - type: sh.keptn.event.notifyticket.triggered
      requests:
        - "curl --request POST --data 'payload={  \"blocks\":
          [    {      \"type\" : \"section\",      \"text\" : {        \"type\":
          \"mrkdwn\",        \"text\" : \"New PagerDuty Incident
          Created\"      }    },    {      \"type\" : \"section\",      \"text\"
          : {        \"type\": \"mrkdwn\",        \"text\" : \"*Project:*
          {{.data.project}}\\n*Service:* {{.data.service}}\\n*Stage:*
          {{.data.stage}}\\n*Type:* {{.type}}\\n*PagerDuty Incident ID*:
          {{.data.openticket.incidentID}}\\n*PagerDutyUrl*:
          {{.data.openticket.incidentURL}}\\n*Bridge:*
          {{.env.secret_slackwebhook_bridgeUrl}}/trace/{{.shkeptncontext}}\"      \
          }    }  ]}'
          https://hooks.slack.com/services/{{.env.secret_slackwebhook_token}}"
      envFrom:
        - name: secret_slackwebhook_token
          secretRef:
            name: slack-webhook
            key: token
        - name: secret_slackwebhook_bridgeUrl
          secretRef:
            name: slack-webhook
            key: bridgeUrl
      subscriptionID: 539ffa72-c336-4aac-8068-94a4826f3ea0
      sendFinished: true
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --request POST --data 'payload={  \"blocks\":
          [    {      \"type\" : \"section\",      \"text\" : {        \"type\":
          \"mrkdwn\",        \"text\" : \"On Demand SLO
          Results\"      }    },    {      \"type\" : \"section\",      \"text\"
          : {        \"type\": \"mrkdwn\",        \"text\" : \"*Project:*
          {{.data.project}}\\n*Service:* {{.data.service}}\\n*Stage:*
          {{.data.stage}}\\n*Result:* {{.data.result}}
          ({{.data.evaluation.score}} / 100)\\n*Bridge:*
          {{.env.secret_slackwebhook_bridgeUrl}}/trace/{{.shkeptncontext}}\\n*P\
          agerDuty Incident ID*: {{.data.openticket.incidentID}}\\n*PagerDuty
          Url*:
          https://dev-dt-demos.pagerduty.com/incidents/{{.data.openticket.incid\
          entID}}\"      }    }  ]}'
          https://hooks.slack.com/services/{{.env.secret_slackwebhook_token}}"
      envFrom:
        - name: secret_slackwebhook_token
          secretRef:
            name: slack-webhook
            key: token
        - name: secret_slackwebhook_bridgeUrl
          secretRef:
            name: slack-webhook
            key: bridgeUrl
      subscriptionID: 3c29d799-45cb-450f-bcc5-376fea867ff9
      sendFinished: true
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"shkeptncontext\":\"{{.shkeptncontext}}\",\
          \"id\":\"{{.id}}\",\"data\":{\"project\":\"{{.data.project}}\",\"serv\
          ice\":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"bridge\":\
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",\"incident\":{\"ProblemID\":\"{{.data.incident.Probl\
          emID}}\",\"PID\":\"{{.data.incident.PID}}\",\"ProblemURL\":\"{{.data.\
          incident.ProblemURL}}\",\"Tags\":\"{{.data.incident.Tags}}\",\"Proble\
          mTitle\":\"{{.data.incident.ProblemTitle}}\",\"State\":\"{{.data.inci\
          dent.State}}\"}}}'
          https://automation.atlassian.com/pro/hooks/f43475548fea82de26cacbe3dd\
          4b7c1ced7638ff"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: d14ba0ae-d186-432b-a127-2ae81e190aca
      sendFinished: false
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Accept: application/vnd.pagerduty+json' --header
          'Authorization: Token token={{.env.secret_pagerduty_apitoken}}'
          --header 'Content-Type: application/json' --header 'From:
          rob.jahn@dynatrace.com' --request POST --data
          '{\"jiraKey\":\"{{.data.release.jiraKey}}\",\"jiraMessage\":\"SLO
          Evaluation for Project: {{.data.project}} Stage: {{.data.stage}}
          Service:
          {{.data.service}}\",\"result\":\"{{.data.result}}\",\"bridge\":\"{{.e\
          nv.secret_bridge_url}}/evaluation/{{.shkeptncontext}}/{{.data.stage}}\
          \"}'
          https://automation.atlassian.com/pro/hooks/9be53cf516a9e3e0af08d3bd0c\
          c215d77c0b985e"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
        - name: secret_pagerduty_apitoken
          secretRef:
            name: pagerduty
            key: api-token
      subscriptionID: 32adcf5e-c436-4cc2-ac19-89f36bfb0bcc
      sendFinished: false
    - type: sh.keptn.event.setfeature.triggered
      requests:
        - "curl --header 'Authorization: token
          {{.env.secret_githubsecret_GITHUBTOKEN}}' --request POST --data
          '{\"event_type\":\"setfeature\",\"client_payload\":{\"type\":\"{{.typ\
          e}}\",\"project\":\"{{.data.project}}\",\"service\":\"{{.data.service\
          }}\",\"stage\":\"{{.data.stage}}\",\"feature\":\"1\",\"id\":\"{{.id}}\
          \",\"shkeptncontext\":\"{{.shkeptncontext}}\"}}'
          https://api.github.com/repos/dt-robertjahn/rob00334-incident-demo/dis\
          patches"
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 533de068-54a5-4e80-91a4-831ebfca13d3
      sendFinished: false
