apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"shkeptncontext\":\"{{.shkeptncontext}}\",\
          \"id\":\"{{.id}}\",\"data\":{\"project\":\"{{.data.project}}\",\"serv\
          ice\":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"bridge\":\
          \"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}\",\"incident\":{\"ProblemID\":\"{{.data.incident.Probl\
          emID}}\",\"PID\":\"{{.data.incident.PID}}\",\"ProblemURL\":\"{{.data.\
          incident.ProblemURL}}\",\"Tags\":\"{{.data.incident.Tags}}\",\"Proble\
          mTitle\":\"{{.data.incident.ProblemTitle}}\",\"State\":\"{{.data.inci\
          dent.State}}\"}}}'
          https://automation.atlassian.com/pro/hooks/f43475548fea82de26cacbe3dd\
          4b7c1ced7638ff"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 385c73cc-ff32-4c56-b46e-f939e145990a
      sendFinished: false
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"data\":{\"project\":\"{{.data.project}}\",\"service\":\"{{.data.s\
          ervice}}\",\"stage\":\"{{.data.stage}}\"},\"shkeptncontext\":\"{{.shk\
          eptncontext}}\",\"id\":\"{{.id}}\",\"type\":\"{{.type}}\",\"incident\
          \":{\"ProblemID\":\"{{.data.incident.ProblemID}}\",\"ProblemTitle\":\
          \"{{.data.incident.ProblemTitle}}\",\"PID\":\"{{.data.incident.PID}}\
          \",\"ProblemURL\":\"{{.data.incident.ProblemURL}}\",\"State\":\"{{.da\
          ta.incident.State}}\",\"Tags\":\"{{.data.incident.Tags}}\",\"bridgeURL\
          \":\"{{.env.secret_bridge_url}}/project/{{.data.project}}/sequence/{{\
          .shkeptncontext}}\"}}'
          https://events.pagerduty.com/x-ere/{{.env.secret_pagerduty_integratio\
          nkey}}"
      envFrom:
        - name: secret_pagerduty_integrationkey
          secretRef:
            name: pagerduty
            key: integration-key
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: cf4bcc2b-f198-40fb-a7a1-0a94e6d9bd5d
      sendFinished: false
    - type: sh.keptn.event.notify.triggered
      requests:
        - "curl --header 'Authorization: Api-Token
          {{.env.secret_dynatraceproblemcomment_token}}' --header 'Content-Type:
          application/json' --request POST --data '{\"message\":\"Opened
          Incident
          [PagerDuty]({{.data.openticket.incidentURL}})\",\"context\":\"cloud-a\
          utomation-webhook\"}'
          https://syh360.dynatrace-managed.com/e/1c819cc7-d7f5-40d9-b90f-b80c86\
          10a392/api/v2/problems/{{.data.incident.PID}}/comments"
      envFrom:
        - name: secret_dynatraceproblemcomment_token
          secretRef:
            name: dynatrace-problem-comment
            key: token
      subscriptionID: 9b8f7fb2-7deb-419c-b8ec-28c8bae3827f
      sendFinished: true
    - type: sh.keptn.event.notifyticket.triggered
      requests:
        - curl --request POST --data
          '{"project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","incident":{"ProblemID":"{{.data.incident.ProblemID}}","ProblemURL":"{{.data.incident.ProblemURL}}","ProblemTitle":"{{.data.incident.ProblemTitle}}","State":"{{.data.incident.State}}","Tags":"{{.data.incident.Tags}}"},"openticket":{"incidentUrl":"{{.data.openticket.incidentUrl}}","incidentNumber":"{{.data.openticket.incidentNumber}}"}}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: e335d827-0ed0-4349-a50b-e51284359394
      sendFinished: true
    - type: sh.keptn.event.notifyslo.triggered
      requests:
        - "curl --header 'Accept: application/vnd.pagerduty+json' --header
          'Authorization: Token token={{.env.secret_pagerduty_apitoken}}'
          --header 'Content-Type: application/json' --header 'From:
          rob.jahn@dynatrace.com' --request POST --data
          '{\"note\":{\"content\":\"SLO Evaluation Results\\nProject:
          {{.data.project}}\\nService: {{.data.service}}\\nStage:
          {{.data.stage}}\\nResult: {{.data.evaluation.result}}\\nScore:
          {{.data.evaluation.score}}\\nBridge:
          {{.env.secret_bridge_url}}/evaluation/{{.shkeptncontext}}/{{.data.sta\
          ge}}\"}}'
          https://api.pagerduty.com/incidents/{{.data.openticket.incidentID}}/n\
          otes"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
        - name: secret_pagerduty_apitoken
          secretRef:
            name: pagerduty
            key: api-token
      subscriptionID: 32adcf5e-c436-4cc2-ac19-89f36bfb0bcc
      sendFinished: true
