apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","openticket":{"incidentNumber":"{{.data.openticket.incidentNumber}}","incidentUrl":"{{.data.openticket.incidentUrl}}"},"evaluation":{"result":"{{.data.result}}
          ({{.data.evaluation.score}} /
          100)"},"incident":{"ProblemID":"{{.data.incident.ProblemID}}","ProblemTitle":"{{.data.incident.ProblemTitle}}","ProblemURL":"{{.data.incident.ProblemURL}}","State":"{{.data.incident.State}}","Tags":"{{.data.incident.Tags}}"}}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: 082734b4-7621-4491-b142-45be85b7547b
    - type: sh.keptn.event.openticket.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"data\":{\"project\":\"{{.data.project}}\",\"service\":\"{{.data.s\
          ervice}}\",\"stage\":\"{{.data.stage}}\"},\"shkeptncontext\":\"{{.shk\
          eptncontext}}\",\"id\":\"{{.id}}\",\"type\":\"{{.type}}\",\"incident\
          \":{\"ProblemID\":\"{{.data.incident.ProblemID}}\",\"ProblemTitle\":\
          \"{{.data.incident.ProblemTitle}}\",\"ProblemURL\":\".data.incident.P\
          roblemURL\",\"State\":\"{{.data.incident.State}}\",\"Tags\":\"{{.data\
          .incident.Tags}}\"}}' http://34.215.238.225:8080/runtask"
      subscriptionID: c0d0f7b9-251d-4438-8122-443d6b1b34d9
    - type: sh.keptn.event.test.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"data\":{\"project\":\"{{.data.project}}\",\"service\":\"{{.data.s\
          ervice}}\",\"stage\":\"{{.data.stage}}\"},\"shkeptncontext\":\"{{.shk\
          eptncontext}}\",\"id\":\"{{.id}}\",\"type\":\"{{.type}}\"}'
          http://34.215.238.225:8080/runtask"
      subscriptionID: 221ad77a-229d-4594-ae30-29820521fb38
    - type: sh.keptn.event.deployment.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"data\":{\"project\":\"{{.data.project}}\",\"service\":\"{{.data.s\
          ervice}}\",\"stage\":\"{{.data.stage}}\"},\"shkeptncontext\":\"{{.shk\
          eptncontext}}\",\"id\":\"{{.id}}\",\"type\":\"{{.type}}\"}'
          http://34.215.238.225:8080/runtask"
      subscriptionID: 2803e5e9-3e82-4528-929f-386f670fabf5
